### ISSUE TITLE
colorspace fastq's

### ISSUE THREAD

**Issue by surgebiswas** [surgebiswas/transcriptome_compression#6]
Some of the fastq files on NCBI SRA are in colorspace format. We need to do a quick check of this and convert to base space if needed. See e.g. SRR566603

**Comment by FriendlyNeighborhoodNematode** [comment]
the 19th field of every query table "platform" contains the sequencing platform that was used in the respective experiment. based on the knowledge that sequencing runs on ILLUMINA sequencers never return colourspace encoded files, a checkpoint is now implemented that will skip to the next run unless the 19th field in this row says "ILLUMINA" (next unless $platform eq "ILLUMINA";)
