### ISSUE TITLE
completion check

### ISSUE THREAD

**Issue by surgebiswas** [surgebiswas/transcriptome_compression#9]
Change the completion check of srafish to check for a populated quant_bias_corrected.sf file.

**Comment by FriendlyNeighborhoodNematode** [comment]
renamed subroutine &check_logfile to &completion_check. it will now first check if the file quant_bias_corrected exists in the passed run directory, and then if this file is bigger than 500KB. returns true if both conditions apply.

sub completion_check {

```
my $complete     = 0;
my $outdir       = shift @_;
my $rundir       = shift @_;
my $filesize;

if (-e "$outdir/$rundir/$run/quant_bias_corrected.sf") {

    $filesize = -s "$outdir/$rundir/$run/quant_bias_corrected.sf";

    $complete = 1 if $filesize >= 500000;
}
return $complete;
```

}
